[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.1"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[prune]
  go-tests = true
  unused-packages = true
